# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update actions listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "wednesday"
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[actions] " (no colon, but a trailing whitespace)
      prefix: "[actions] "

  - package-ecosystem: "composer"
    directory: "/" # Location of package manifests
    schedule:
      day: "wednesday"
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[composer] " (no colon, but a trailing whitespace)
      prefix: "[composer] "

  # Update npm and pnpm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      day: "wednesday"
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[npm] " (no colon, but a trailing whitespace)
      prefix: "[npm] "
    # Use `ignore` to specify dependencies that should not be updated
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
